refact: migrate to devbin64

diff --git a/GIT/skeletons/dev-generic/bin/dev-TASK b/GIT/skeletons/dev-generic/bin/dev-TASK
--- a/GIT/skeletons/dev-generic/bin/dev-TASK
+++ b/GIT/skeletons/dev-generic/bin/dev-TASK
@@ -1,19 +1,25 @@
 #!/usr/bin/env bash
 #
-# X_TASK_DESCRIPTION_X
+# Dev / X_TASK_X / X_COMPONENT_X / X_TASK_DESCRIPTION_X
 #
-# * Template: 1.2.0
+# * Template: 1.3.0
 #
 
 #
 # Imports
 #
 
-[[ ! -f 'bin/dev-set' ]] && echo "Error: script must be run from the project's root path" && exit 1
 # shellcheck source=bin/dev-set
-source ./bin/dev-set || exit 1
+source ./bin/dev-set || { echo 'dev-set:Error: unable to load dev environment' 2>&1 && exit 1; }
 # shellcheck source=lib/bl64/bashlib64-core.bash
-source "${DEV_CICD_BASHLIB64}/bashlib64-core.bash" || exit 1
+source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-core.bash" || exit 1
+
+#
+# Globals
+#
+
+# Dev / Enable debugging? Set to YES to enable
+export DEV_CICD_DEBUG="${DEV_CICD_DEBUG:-}"
 
 #
 # Functions
@@ -25,15 +31,19 @@ function dev_X_TASK_X() {
   # X_FUNCTION_PLACEHOLDER_X
 }
 
+function dev_X_TASK_X_initialize() {
+  bl64_dbg_app_show_function
+  # X_INITILIZE_PLACEHOLDER_X
+}
+
 #
 # Main
 #
 
 [[ -n "$DEV_CICD_DEBUG" ]] && bl64_dbg_all_enable
-
-# X_INIT_PLACEHOLDER_X
+dev_X_TASK_X_initialize || exit $?
 
 bl64_msg_all_enable_verbose
-bl64_msg_show_batch_start 'X_TASK_X'
+bl64_msg_show_batch_start 'dev-X_TASK_X-X_COMPONENT_X'
 dev_X_TASK_X
-bl64_msg_show_batch_finish $? 'X_TASK_X'
+bl64_msg_show_batch_finish $? 'dev-X_TASK_X-X_COMPONENT_X'
